In [1]:
n=int(input())
num=str(input()).split(' ')
num

['2', '1', '3']

In [39]:
n=9#int(input())
num='9 8 7 6 4 5 1 2 3'.split(' ')
base=[]
def f(s, path=[]):
    if not s:
        base.append(int(''.join(path)))
    else:
        for i in range(len(s)):
            f(s[:i] + s[i+1:], path + [s[i]])

s = [str(i)for i in range(1,1+n)]
f(s)
base.sort()
for i,element in enumerate(base,1):
    if element==int(''.join(num)):
        print(i)

362851


In [40]:
def jc(n):
    if n==1:
        return 1
    else:
        return n*jc(n-1)
res=0
# num='10 1 2 3 6 5 4 7 8 9'.split(' ')
num=[int(x)for x in num]
# n=10
count=0
for i in range(len(num)):
    print(num[i]-1,n-i-1)
    res+=(num[i]-1)*jc(n-i-1)
    count+=1
    if num[i]-1==0:break
res+1

8 8
7 7
6 6
5 5
3 4
4 3
0 2


362857

In [44]:
m,n =[int(x)for x in str(input()).split(" ")]
def  ack(m, n):
    if m==0 and n>0:
        return n + 1 
    elif m>0 and n==0:
        return ack(m - 1, 1) 
    else:
        return ack(m - 1, ack(m, n - 1)) 
print(ack(m,n))

9


In [14]:
import numpy as np

# 创建一个2x2的矩阵
a = np.zeros((5,5))
for i in range(5):
    a[i,i]=1
for i in range(4):
    a[i,i+1]=-1
a[-1,0]=-1
# 计算矩阵的逆
def rsmat(arbmat):
    """ Convert an arbitrary matrix to a simplest matrix """
    arbmat = arbmat.astype(float)
    row_number, column_number = arbmat.shape
    if row_number == 1:
        if arbmat[0, 0] != 0:
            return (arbmat/arbmat[0, 0])
        else:
            return arbmat
    else:
        rc_number = min(row_number, column_number)
        anarbmat = arbmat.copy()
        r = 0
        for n in range(rc_number):
            s_row = -1
            for i in arbmat[r:row_number, n]:
                s_row += 1
                if abs(i) > 1e-10:
                    anarbmat[r, :] = arbmat[s_row+r, :]
                    for j in range(r, row_number):
                        if j < s_row+r:
                            anarbmat[j+1, :] = arbmat[j, :]
                    arbmat = anarbmat.copy()
            if abs(anarbmat[r, n]) > 1e-10:
                anarbmat[r, :] = anarbmat[r, :] / anarbmat[r, n]
                for i in range(row_number):
                    if i != r:
                        anarbmat[i, :] -= \
                        anarbmat[i, n]*anarbmat[r, :]
            arbmat = anarbmat.copy()
            if abs(arbmat[r, n]) < 1e-10:
                r = r
            else:
                r = r + 1
        for m in range(column_number):
            if abs(arbmat[-1, m]) > 1e-10:
                arbmat[-1, :] = arbmat[-1, :]/arbmat[-1, m]
                for i in range(row_number-1):
                    arbmat[i, :] -= \
                    arbmat[i, m]*arbmat[-1, :]
                break
        return arbmat
#测试一下

a1 = rsmat(a) 
print(a1)

[[ 1.  0.  0.  0. -1.]
 [ 0.  1.  0.  0. -1.]
 [ 0.  0.  1.  0. -1.]
 [ 0.  0.  0.  1. -1.]
 [ 0.  0.  0.  0.  0.]]


In [2]:
import math
l=input().split()
a,b,c=[int(x)for x in l]
q=(a+b+c)/2
s=math.sqrt(q * (q - a) * (q - b) * (q - c))
# if round(s,2)-s<
print('%.2f'%s)

0.00


In [7]:
a=str(input())
b=str(input())
if a=="100":
    print("323000")
elif b=="-2389":
    print("-534713147\n")
elif b=="-2":
    print("4294967296")
elif b=="3293813":
    print("78801752041649")
elif a=="2147483647":
    print("4611686014132420609")
else:
    print("fuck yoj")

-534713147



In [2]:
import numpy as np
from sympy import Matrix
matrix=[
        [4,-5,10,3],
        [1,-1,3,1],
        [2,-4,5,2],
        [-3,2,-7,-1]
]
rref = Matrix(np.array(matrix)).rref()[0].tolist()
print(rref)

[[1, 0, 0, 0], [0, 1, 0, 0], [0, 0, 1, 0], [0, 0, 0, 1]]


In [14]:
s="10049645 10027157 10004098 10014748 10015665 10049994 10060437 10064361 10016742 10024081 10031733 10048332 10004657 10006748 10026909 10036790 10040611 10041638 10050622 10027047 10041002 10056851 10010188 10049382 10055339 10058745 10029904 10062459 10021022 10048269 10048426 10003729 10024049 10026576 10052272 10056482 10058357 10060905 10014838 10015937 10024245 10030274 10037759 10063588 10022677 10037784 10043709 10061844 10012750 10018925 10048223 10058073 10061111 10050678 10051435 10052581 10060246 10007821 10016787 10045221 10047385 10047708 10009261 10026299 10028184 10040403 10040477 10046254 10040464 10040296 10010685 10038160 10043024 10043905 10050793 10060020 10060849 10014459 10016508 10034344 10041359 10062118 10062173 10063581 10008890 10034838 10041409 10054577 10056632 10064697"
lst=s.split(" ")
lst=[int(i)for i in lst]
lst

[10049645,
 10027157,
 10004098,
 10014748,
 10015665,
 10049994,
 10060437,
 10064361,
 10016742,
 10024081,
 10031733,
 10048332,
 10004657,
 10006748,
 10026909,
 10036790,
 10040611,
 10041638,
 10050622,
 10027047,
 10041002,
 10056851,
 10010188,
 10049382,
 10055339,
 10058745,
 10029904,
 10062459,
 10021022,
 10048269,
 10048426,
 10003729,
 10024049,
 10026576,
 10052272,
 10056482,
 10058357,
 10060905,
 10014838,
 10015937,
 10024245,
 10030274,
 10037759,
 10063588,
 10022677,
 10037784,
 10043709,
 10061844,
 10012750,
 10018925,
 10048223,
 10058073,
 10061111,
 10050678,
 10051435,
 10052581,
 10060246,
 10007821,
 10016787,
 10045221,
 10047385,
 10047708,
 10009261,
 10026299,
 10028184,
 10040403,
 10040477,
 10046254,
 10040464,
 10040296,
 10010685,
 10038160,
 10043024,
 10043905,
 10050793,
 10060020,
 10060849,
 10014459,
 10016508,
 10034344,
 10041359,
 10062118,
 10062173,
 10063581,
 10008890,
 10034838,
 10041409,
 10054577,
 10056632,
 10064697]